spec:
  template:
    spec:
      # Declare a volume mounting the config map
      volumes:
        - configMap:
            # Name of the config map
            name: insult-config
            optional: true
            # Define the items from the config map to mount
            items:
            - key: insult-config.json
              path: insult-config.json
            # Volume name (used as reference below)
          name: config
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: VERTX_CONFIG_PATH
              value: '/deployments/conf/insult-config.json'
          volumeMounts:
            - name: config
              mountPath: /deployments/conf
